from enum import StrEnum
from .errors import DomainError


class OrderState(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    RISK_CHECKED = "RISK_CHECKED"
    PAYMENT_RESERVED = "PAYMENT_RESERVED"
    SUPPLIER_ORDER_PENDING = "SUPPLIER_ORDER_PENDING"
    SUPPLIER_ORDERED = "SUPPLIER_ORDERED"
    SUPPLIER_PAID = "SUPPLIER_PAID"
    SHIPMENT_PENDING = "SHIPMENT_PENDING"
    SHIPPED = "SHIPPED"
    DELIVERED = "DELIVERED"
    SETTLEMENT_PENDING = "SETTLEMENT_PENDING"
    SETTLED = "SETTLED"
    CLOSED = "CLOSED"
    CANCEL_REQUESTED = "CANCEL_REQUESTED"
    CANCELLED = "CANCELLED"
    CLAIM_OPEN = "CLAIM_OPEN"
    SUPPLIER_CLAIM_OPEN = "SUPPLIER_CLAIM_OPEN"
    REFUND_PENDING = "REFUND_PENDING"
    REFUNDED = "REFUNDED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    SUPPLIER_FAILED = "SUPPLIER_FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    FAILED = "FAILED"


NORMAL = [s.value for s in list(OrderState)[:14]]
ALLOWED = {s.value: set() for s in OrderState}
for before, after in zip(NORMAL, NORMAL[1:]):
    ALLOWED[before].add(after)
for state in NORMAL[:-3]:
    ALLOWED[state].update({"CANCEL_REQUESTED", "MANUAL_REVIEW"})
ALLOWED["SUPPLIER_ORDER_PENDING"].add("SUPPLIER_FAILED")
ALLOWED["SUPPLIER_ORDERED"].add("PAYMENT_FAILED")
ALLOWED["CANCEL_REQUESTED"].update({"CANCELLED", "MANUAL_REVIEW"})
ALLOWED["MANUAL_REVIEW"].update({"VALIDATING", "CANCEL_REQUESTED", "FAILED"})
ALLOWED["PAYMENT_FAILED"].add("MANUAL_REVIEW")
ALLOWED["SUPPLIER_FAILED"].add("MANUAL_REVIEW")
ALLOWED["DELIVERED"].add("CLAIM_OPEN")
ALLOWED["CLAIM_OPEN"].update({"SUPPLIER_CLAIM_OPEN", "MANUAL_REVIEW"})
ALLOWED["SUPPLIER_CLAIM_OPEN"].update({"REFUND_PENDING", "MANUAL_REVIEW"})
ALLOWED["REFUND_PENDING"].update({"REFUNDED", "MANUAL_REVIEW"})
ALLOWED["REFUNDED"].add("SETTLEMENT_PENDING")
EARLY_CANCEL = set(NORMAL[:5]) | {"MANUAL_REVIEW"}


def validate_transition(current: str, target: str) -> None:
    if current == target and current in ALLOWED:
        return
    if target not in ALLOWED.get(current, set()):
        raise DomainError("INVALID_ORDER_TRANSITION")
